name: cv_card
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ava.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf
